// Copyright 2026 The Ptah Operator Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// crdreference renders the field reference for every custom resource this
// operator ships.
//
// The source is the CRD schema rather than the Go source, because the schema is
// what the API server enforces: a type, a required list, an enum, a default and
// a list semantic all reach a reader the way a cluster will apply them. The
// schemas it reads are generated with descriptions, which the shipped ones drop
// (`crd:maxDescLen=0`), so the page carries the doc comments the Go types hold
// without the CRDs in etcd carrying them too.
//
// The pages are checked in and regenerated by `make docs-reference`. Running it
// without -write refuses a page that no longer matches the API, which is how a
// field added to a Go type cannot leave the reference behind.
package main

import (
	"bytes"
	"errors"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"

	apiextensionsv1 "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
	"sigs.k8s.io/yaml"
)

func main() {
	if err := run(os.Args[1:], os.Stdout); err != nil {
		fmt.Fprintf(os.Stderr, "crdreference: %v\n", err)
		os.Exit(1)
	}
}

func run(args []string, out *os.File) error {
	flags := flag.NewFlagSet("crdreference", flag.ContinueOnError)
	crdDir := flags.String("crds", "", "directory of CRD YAML generated with descriptions")
	outDir := flags.String("out", "", "directory the reference pages are written to")
	examplesDir := flags.String("examples", "",
		"directory of example fragments, one <kind>.md per resource")
	write := flags.Bool("write", false, "write the pages instead of checking them")
	requireDescriptions := flags.Bool("require-descriptions", false,
		"refuse a field whose Go type carries no doc comment")
	if err := flags.Parse(args); err != nil {
		return err
	}
	if *crdDir == "" || *outDir == "" || *examplesDir == "" {
		return errors.New("-crds, -out and -examples are all required")
	}

	entries, err := filepath.Glob(filepath.Join(*crdDir, "*.yaml"))
	if err != nil {
		return err
	}
	if len(entries) == 0 {
		return fmt.Errorf("%s holds no CRD", *crdDir)
	}
	sort.Strings(entries)

	var undocumented []string
	stale := 0
	for _, entry := range entries {
		document, err := os.ReadFile(entry)
		if err != nil {
			return err
		}
		var crd apiextensionsv1.CustomResourceDefinition
		if err := yaml.UnmarshalStrict(document, &crd); err != nil {
			return fmt.Errorf("%s: %w", entry, err)
		}
		examples, err := readExamples(*examplesDir, crd.Spec.Names.Kind)
		if err != nil {
			return err
		}
		page, rows, err := render(&crd, examples)
		if err != nil {
			return fmt.Errorf("%s: %w", entry, err)
		}
		for _, row := range rows {
			if row.Description == "" {
				undocumented = append(undocumented,
					fmt.Sprintf("%s.%s", crd.Spec.Names.Kind, row.Path))
			}
		}
		target := filepath.Join(*outDir, pageName(crd.Spec.Names.Kind))
		if *write {
			if err := os.MkdirAll(*outDir, 0o755); err != nil {
				return err
			}
			if err := os.WriteFile(target, []byte(page), 0o644); err != nil {
				return err
			}
			fmt.Fprintf(out, "crdreference: wrote %s (%d fields)\n", target, len(rows))
			continue
		}
		existing, err := os.ReadFile(target)
		if err != nil {
			return fmt.Errorf("%s is missing; run make docs-reference", target)
		}
		if string(existing) != page {
			fmt.Fprintf(out, "crdreference: %s is stale; run make docs-reference\n", target)
			stale++
			continue
		}
		fmt.Fprintf(out, "crdreference: OK %s (%d fields)\n", target, len(rows))
	}
	if stale > 0 {
		return fmt.Errorf("%d reference page(s) no longer match the API", stale)
	}
	if *requireDescriptions && len(undocumented) > 0 {
		return fmt.Errorf("%d API field(s) carry no doc comment: %s",
			len(undocumented), strings.Join(undocumented, ", "))
	}
	if len(undocumented) > 0 {
		fmt.Fprintf(out, "crdreference: %d field(s) carry no doc comment\n", len(undocumented))
	}
	return nil
}

// row is one field of one resource, at its dotted path.
type row struct {
	Path        string
	Type        string
	Description string
	// Narrows are the messages of the validations the enclosing object
	// declares that name this field. A field's own description comes from the
	// type it is declared as, and for an embedded Kubernetes selector that
	// description describes the generic type rather than what this API
	// accepts -- corev1.SecretKeySelector says its name may be empty for
	// backward compatibility, and every selector here is narrowed to refuse
	// exactly that.
	Narrows []string
}

func pageName(kind string) string {
	return strings.ToLower(kind) + ".md"
}

// readExamples returns the example fragment written for one kind.
//
// The fragment is required rather than optional: a resource with no worked
// example is the gap this section exists to close, so a new kind fails here
// instead of publishing a page of field names and nothing to copy.
func readExamples(dir, kind string) (string, error) {
	path := filepath.Join(dir, strings.ToLower(kind)+".md")
	fragment, err := os.ReadFile(path)
	if err != nil {
		return "", fmt.Errorf("%s: every resource owes the reference an example: %w", kind, err)
	}
	text := strings.TrimSpace(string(fragment))
	if text == "" {
		return "", fmt.Errorf("%s is empty", path)
	}
	return text, nil
}

// render turns one CRD into its page and the rows it holds.
func render(crd *apiextensionsv1.CustomResourceDefinition, examples string) (string, []row, error) {
	version, err := servedVersion(crd)
	if err != nil {
		return "", nil, err
	}
	if version.Schema == nil || version.Schema.OpenAPIV3Schema == nil {
		return "", nil, fmt.Errorf("version %s carries no schema", version.Name)
	}
	kind := crd.Spec.Names.Kind
	root := version.Schema.OpenAPIV3Schema

	var spec, status []row
	if property, ok := root.Properties["spec"]; ok {
		spec = walk("", &property)
		annotate(spec, narrowings(&property))
	}
	if property, ok := root.Properties["status"]; ok {
		status = walk("", &property)
		annotate(status, narrowings(&property))
	}

	var page bytes.Buffer
	fmt.Fprintf(&page, "---\ntitle: %s\ndescription: Every field of the %s resource, generated from the API types.\n---\n\n",
		kind, kind)
	scope := "namespaced"
	if crd.Spec.Scope == apiextensionsv1.ClusterScoped {
		scope = "cluster-scoped"
	}
	fmt.Fprintf(&page, "`%s` is a %s resource in `%s`, served as `%s`.\n\n",
		kind, scope, crd.Spec.Group, version.Name)
	fmt.Fprintf(&page, "This page is generated from the API types by `make docs-reference`. "+
		"The shipped CRDs carry no descriptions, so this is where the field documentation lives.\n\n")

	// The examples come before the field tables: a reader who arrives at a
	// resource wants the shape of it before the hundred and sixty rows that
	// spell out every field of it.
	fmt.Fprintf(&page, "%s\n\n", examples)

	writeSection(&page, "spec", spec)
	writeSection(&page, "status", status)

	rows := append(append([]row{}, spec...), status...)
	return page.String(), rows, nil
}

func writeSection(page *bytes.Buffer, name string, rows []row) {
	fmt.Fprintf(page, "## %s\n\n", name)
	if len(rows) == 0 {
		fmt.Fprintf(page, "This resource declares no `%s`.\n\n", name)
		return
	}
	fmt.Fprintf(page, "| Field | Type | What it does |\n| --- | --- | --- |\n")
	for _, entry := range rows {
		fmt.Fprintf(page, "| `%s.%s` | %s | %s |\n",
			name, entry.Path, entry.Type, cell(describe(entry)))
	}
	fmt.Fprintf(page, "\n")
}

// describe is the field's own description followed by what the enclosing
// object refuses. The second half is the rule's own message rather than a
// reading of its expression: this generator finds which rules name a field and
// does not interpret what they compute.
func describe(entry row) string {
	if len(entry.Narrows) == 0 {
		return entry.Description
	}
	// The requirement comes first. A field's own description is the one its
	// declared type carries, and for an embedded Kubernetes selector that text
	// says the name may be empty for backward compatibility -- which this API
	// refuses. A reader who meets the refusal first cannot read the sentence
	// after it as the contract.
	return "This resource requires: " + strings.Join(entry.Narrows, "; ") + ". " +
		strings.TrimSpace(entry.Description)
}

// narrowings maps a field path to the messages of the validations that name
// it. A rule is attributed to every path it mentions as self.<dotted.path>,
// which is what a reader needs in order to find the rule; what the rule
// computes is its message's business.
func narrowings(schema *apiextensionsv1.JSONSchemaProps) map[string][]string {
	notes := map[string][]string{}
	for _, validation := range schema.XValidations {
		message := strings.TrimSpace(validation.Message)
		if message == "" {
			continue
		}
		for _, path := range selfReferences(validation.Rule) {
			if !contains(notes[path], message) {
				notes[path] = append(notes[path], message)
			}
		}
	}
	return notes
}

// selfReferences are the dotted field paths a rule names, and every prefix of
// each: a rule about target.urlFrom.name is a rule a reader of target.urlFrom
// needs to know about.
func selfReferences(rule string) []string {
	var paths []string
	for _, match := range selfReference.FindAllStringSubmatch(rule, -1) {
		segments := strings.Split(match[1], ".")
		for index := range segments {
			path := strings.Join(segments[:index+1], ".")
			if !contains(paths, path) {
				paths = append(paths, path)
			}
		}
	}
	return paths
}

var selfReference = regexp.MustCompile(`\bself\.([A-Za-z][A-Za-z0-9]*(?:\.[A-Za-z][A-Za-z0-9]*)*)`)

// annotate attaches each row the notes recorded for its path.
func annotate(rows []row, notes map[string][]string) {
	for index := range rows {
		rows[index].Narrows = notes[rows[index].Path]
	}
}

// cell renders a description into one table cell: Markdown tables have no rows
// of their own, so the newlines a doc comment carries become spaces and the
// pipes become text.
func cell(description string) string {
	flat := strings.Join(strings.Fields(description), " ")
	return strings.ReplaceAll(flat, "|", "\\|")
}

func servedVersion(crd *apiextensionsv1.CustomResourceDefinition) (apiextensionsv1.CustomResourceDefinitionVersion, error) {
	for _, version := range crd.Spec.Versions {
		if version.Storage {
			return version, nil
		}
	}
	return apiextensionsv1.CustomResourceDefinitionVersion{},
		fmt.Errorf("%s names no storage version", crd.Name)
}

// walk lists one schema's fields, depth first, at their dotted paths.
func walk(prefix string, schema *apiextensionsv1.JSONSchemaProps) []row {
	names := make([]string, 0, len(schema.Properties))
	for name := range schema.Properties {
		names = append(names, name)
	}
	sort.Strings(names)

	rows := make([]row, 0, len(names))
	for _, name := range names {
		property := schema.Properties[name]
		path := name
		if prefix != "" {
			path = prefix + "." + name
		}
		rows = append(rows, row{
			Path:        path,
			Type:        describeType(&property, contains(schema.Required, name)),
			Description: property.Description,
		})
		switch {
		case property.Type == "object" && len(property.Properties) > 0:
			rows = append(rows, walk(path, &property)...)
		case property.Type == "array" && property.Items != nil && property.Items.Schema != nil &&
			len(property.Items.Schema.Properties) > 0:
			rows = append(rows, walk(path+"[]", property.Items.Schema)...)
		}
	}
	return rows
}

// describeType says what a reader may put in the field: the type, whether it is
// required, and the values the schema accepts where it names them.
func describeType(schema *apiextensionsv1.JSONSchemaProps, required bool) string {
	kind := schema.Type
	if kind == "array" && schema.Items != nil && schema.Items.Schema != nil {
		kind = "[]" + schema.Items.Schema.Type
	}
	if kind == "" {
		kind = "any"
	}
	parts := []string{"`" + kind + "`"}
	if required {
		parts = append(parts, "required")
	}
	if len(schema.Enum) > 0 {
		values := make([]string, 0, len(schema.Enum))
		for _, value := range schema.Enum {
			values = append(values, "`"+strings.Trim(string(value.Raw), `"`)+"`")
		}
		parts = append(parts, "one of "+strings.Join(values, ", "))
	}
	if schema.Default != nil {
		parts = append(parts, "default `"+strings.Trim(string(schema.Default.Raw), `"`)+"`")
	}
	return strings.Join(parts, ", ")
}

func contains(values []string, want string) bool {
	for _, value := range values {
		if value == want {
			return true
		}
	}
	return false
}
