package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/types"
)

// ImmutableObjectReference binds a name to the UID that existed when the
// reference was created, preventing delete-and-recreate aliasing.
type ImmutableObjectReference struct {
	// Name of the referenced object in the same namespace.
	Name string `json:"name"`
	// UID the object had when the reference was written. An object deleted and
	// recreated under the same name is a different object, and this says so.
	UID types.UID `json:"uid"`
}

// PlanChunkReference identifies one ordered immutable PtahSchemaPlanChunk.
type PlanChunkReference struct {
	// Name of the PtahSchemaPlanChunk holding this chunk. An Apply projects
	// the chunk into its Pod through an immutable ConfigMap of the same name.
	Name string `json:"name"`
	// Index of this chunk in the plan, counting from zero. The chunks are
	// concatenated in this order and in no other.
	// +kubebuilder:validation:Minimum=0
	// +kubebuilder:validation:Maximum=15
	Index int32 `json:"index"`
	// Digest of this chunk's bytes, checked when the plan is read back.
	Digest string `json:"digest"`
	// Size of this chunk in bytes, checked with the digest.
	// +kubebuilder:validation:Minimum=1
	// +kubebuilder:validation:Maximum=524288
	Size int32 `json:"size"`
}

// PrivilegeChange is one kind of authority a plan statement grants, revokes,
// delegates or rebinds. It names the kind of change, never the object, the role
// or the statement.
//
//   - Grant: a privilege granted on an object, default privileges included.
//   - Revoke: a privilege revoked from an object.
//   - RoleMembership: a role granted to or revoked from a role or user.
//   - Role: a role, user or group created, altered or dropped, or assumed for
//     the rest of the session with SET ROLE or SET SESSION AUTHORIZATION.
//   - Ownership: an object given to another owner.
//   - RowSecurityPolicy: a row-security policy created, altered or dropped, or
//     row security switched off or unforced on a table.
//   - SecurityDefiner: code set to run with its owner's rights rather than its
//     caller's, which a MySQL or MariaDB routine does unless it says SQL
//     SECURITY INVOKER.
//   - Definer: a MySQL DEFINER clause naming the account a view, routine,
//     trigger or event runs as.
//   - FunctionReplacement: CREATE OR REPLACE of a function or procedure, which
//     can rewrite code that policies, triggers and other roles already call.
//
// +kubebuilder:validation:Enum=Grant;Revoke;RoleMembership;Role;Ownership;RowSecurityPolicy;SecurityDefiner;Definer;FunctionReplacement
type PrivilegeChange string

const (
	PrivilegeChangeGrant               PrivilegeChange = "Grant"
	PrivilegeChangeRevoke              PrivilegeChange = "Revoke"
	PrivilegeChangeRoleMembership      PrivilegeChange = "RoleMembership"
	PrivilegeChangeRole                PrivilegeChange = "Role"
	PrivilegeChangeOwnership           PrivilegeChange = "Ownership"
	PrivilegeChangeRowSecurityPolicy   PrivilegeChange = "RowSecurityPolicy"
	PrivilegeChangeSecurityDefiner     PrivilegeChange = "SecurityDefiner"
	PrivilegeChangeDefiner             PrivilegeChange = "Definer"
	PrivilegeChangeFunctionReplacement PrivilegeChange = "FunctionReplacement"
)

// PtahSchemaPlanSpec is generated by the controller and immutable thereafter.
// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="a plan is immutable; generate a new plan instead"
type PtahSchemaPlanSpec struct {
	// ContractVersion versions plan publication and reconstruction separately
	// from the Kubernetes API version. Version 3 is the only one.
	// +kubebuilder:validation:Enum=3
	ContractVersion int32 `json:"contractVersion"`

	// SchemaRef is the PtahSchema this plan was computed for.
	SchemaRef ImmutableObjectReference `json:"schemaRef"`

	// Fingerprint is the complete approval identity of this plan: every binding
	// below hashed together. An approval names this value, and an apply runs
	// only while the live bindings still produce it.
	Fingerprint string `json:"fingerprint"`
	// ContentDigest is the digest of the plan bytes the chunks reconstruct.
	ContentDigest string `json:"contentDigest"`
	// Size is the length of those bytes, summed across the chunks.
	// +kubebuilder:validation:Minimum=1
	// +kubebuilder:validation:Maximum=8388608
	Size int64 `json:"size"`

	// ArtifactDigest is the OCI artifact this plan was computed from, pinned to
	// content rather than to the tag it was resolved through.
	ArtifactDigest string `json:"artifactDigest"`
	// CoordinationDigest is the database realm this plan takes its turn in: the
	// engine and the coordination key, hashed. Resources that share it never
	// run against the database at the same time.
	CoordinationDigest string `json:"coordinationDigest"`
	// TargetIdentityDigest identifies the database this plan was computed
	// against without carrying anything that could reach it.
	TargetIdentityDigest string `json:"targetIdentityDigest"`
	// ActualStateFingerprint is the observed database state the plan was
	// computed from. Drift since then retires the plan rather than applying it.
	ActualStateFingerprint string `json:"actualStateFingerprint"`
	// DesiredStateFingerprint is the state the verified artifact declared when
	// the plan was computed.
	DesiredStateFingerprint string `json:"desiredStateFingerprint"`
	// PolicyFingerprint is the spec.policy the plan was computed under. Editing
	// the policy -- a protected table included -- retires a plan waiting for a
	// person rather than letting it apply under rules nobody approved.
	PolicyFingerprint string `json:"policyFingerprint"`
	// VerificationPolicyUID is the policy object that accepted the artifact.
	VerificationPolicyUID types.UID `json:"verificationPolicyUID"`
	// VerificationPolicyDigest is that policy's content, so replacing the
	// object or editing it in place both retire the plan.
	VerificationPolicyDigest string `json:"verificationPolicyDigest"`
	// ExecutionBindingID is the execution epoch the plan was computed under. It
	// changes whenever a component that decides what the plan means when it
	// runs changes -- the controller-state version, the Ptah version, the
	// executor image or the runner protocol -- even when a rollout returns to
	// byte-identical versions. A manager upgrade that changes none of them
	// keeps it, and the plan stays applicable.
	// +kubebuilder:validation:Pattern=`^v1-[0-9a-f]{32}$`
	ExecutionBindingID string `json:"executionBindingID"`
	// ControllerImage is the digest-pinned manager that published this plan.
	// It is a record, not a binding: the fingerprint leaves it out, and a
	// later manager may apply the plan.
	// +kubebuilder:validation:Pattern=`^[^[:space:]@]+@sha256:[0-9a-f]{64}$`
	ControllerImage string `json:"controllerImage"`
	// ControllerRevision is that manager's revision, recorded the same way.
	// +kubebuilder:validation:MinLength=1
	// +kubebuilder:validation:MaxLength=128
	// +kubebuilder:validation:Pattern=`^[^[:space:][:cntrl:]]([^[:cntrl:]]*[^[:space:][:cntrl:]])?$`
	ControllerRevision string `json:"controllerRevision"`
	// ControllerStateVersion is the state semantics that manager writes, so a
	// plan is never applied by a controller that reads status differently.
	// +kubebuilder:validation:Minimum=1
	ControllerStateVersion int32 `json:"controllerStateVersion"`
	// PtahVersion is the Ptah build that computed this plan, as the executor
	// image reports it.
	PtahVersion string `json:"ptahVersion"`
	// ExecutorImage is the digest-pinned image that ran Ptah.
	ExecutorImage string `json:"executorImage"`
	// RunnerImage is the digest-pinned runner image of the manager that
	// published this plan. Like the manager's own identity it is recorded and
	// not bound: the runner is built from the operator's source, and what it
	// enforces is versioned by RunnerProtocolVersion.
	RunnerImage string `json:"runnerImage"`
	// RunnerProtocolVersion is the runner protocol the plan binds: what the
	// runner enforces inside the Pod and the result frame it returns. A runner
	// answering in another version has its result rejected rather than
	// interpreted.
	RunnerProtocolVersion int32 `json:"runnerProtocolVersion"`

	// Dialect is the SQL dialect the statements are written in.
	Dialect string `json:"dialect"`
	// Destructive says the plan drops or rewrites something. Such a plan needs
	// spec.policy.allowDestructive and an approval naming these exact bytes.
	Destructive bool `json:"destructive"`
	// PrivilegeChanges names the kinds of authority the plan's statements
	// change: privileges granted or revoked, role membership, roles, owners,
	// row-security policies and definer rights. A plan that lists any needs an
	// approval naming these exact bytes whatever spec.policy.apply says, so
	// apply: Always does not grant access on its own.
	//
	// The operator reads the kinds from the SQL itself, independently of the
	// severity Ptah gave each statement, and only ever adds to a plan's class.
	// It names kinds and nothing else: no object, no role and no text. Read
	// the statements with kubectl ptah plan.
	// +optional
	// +listType=set
	// +kubebuilder:validation:MaxItems=16
	PrivilegeChanges []PrivilegeChange `json:"privilegeChanges,omitempty"`
	// StatementCount is how many statements the plan holds. Read them with
	// kubectl ptah plan rather than by fetching the chunks.
	StatementCount int32 `json:"statementCount"`

	// Chunks are the PtahSchemaPlanChunk objects the plan bytes are stored in.
	// The plan is the concatenation of their data in index order, and nothing
	// reads them without checking each digest and size.
	// +kubebuilder:validation:MinItems=1
	// +kubebuilder:validation:MaxItems=16
	// +listType=map
	// +listMapKey=index
	Chunks []PlanChunkReference `json:"chunks"`
}

// PtahSchemaPlanStatus is the commit record for non-transactional chunk
// publication. Approval and apply require Ready=True.
type PtahSchemaPlanStatus struct {
	// ObservedGeneration is the plan generation this status was written for.
	ObservedGeneration int64 `json:"observedGeneration,omitempty"`
	// PublishedChunks are the PtahSchemaPlanChunk objects that were found to
	// exist, by UID, before Ready became true. Chunk publication is not
	// transactional, so this is the record that every chunk the manifest names
	// was really written.
	// +kubebuilder:validation:MaxItems=16
	// +listType=map
	// +listMapKey=index
	PublishedChunks []PublishedPlanChunkStatus `json:"publishedChunks,omitempty"`
	// Conditions carry Ready, which is what approval and apply require.
	Conditions []metav1.Condition `json:"conditions,omitempty"`
}

// PublishedPlanChunkStatus binds the immutable manifest to the concrete
// PtahSchemaPlanChunk instances verified before Ready became true.
type PublishedPlanChunkStatus struct {
	// Name of the PtahSchemaPlanChunk that was verified.
	Name string `json:"name"`
	// UID it had when it was verified, so a chunk deleted and recreated is not
	// mistaken for the one the plan was published with.
	UID types.UID `json:"uid"`
	// Index of the chunk this record is for.
	// +kubebuilder:validation:Minimum=0
	// +kubebuilder:validation:Maximum=15
	Index int32 `json:"index"`
}

const ConditionPlanStorageReady = "Ready"

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:resource:shortName=ptahplan
// +kubebuilder:printcolumn:name="Schema",type=string,JSONPath=`.spec.schemaRef.name`
// +kubebuilder:printcolumn:name="Fingerprint",type=string,JSONPath=`.spec.fingerprint`
// +kubebuilder:printcolumn:name="Statements",type=integer,JSONPath=`.spec.statementCount`
// +kubebuilder:printcolumn:name="Destructive",type=boolean,JSONPath=`.spec.destructive`
// +kubebuilder:printcolumn:name="Privileges",type=string,JSONPath=`.spec.privilegeChanges`
// +kubebuilder:printcolumn:name="Age",type=date,JSONPath=`.metadata.creationTimestamp`
type PtahSchemaPlan struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   PtahSchemaPlanSpec   `json:"spec"`
	Status PtahSchemaPlanStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true
type PtahSchemaPlanList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []PtahSchemaPlan `json:"items"`
}
