package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/types"
)

// PlannedMigration is one migration a plan selected, as the artifact declares
// it and the database will record it.
type PlannedMigration struct {
	// Version is the migration's numeric version.
	// +kubebuilder:validation:Minimum=1
	Version int64 `json:"version"`

	// VersionKey is the exact revision identity. A version does not identify a
	// row on its own: an Atlas repeatable migration carries an opaque token
	// rather than a decimal spelling.
	// +kubebuilder:validation:MaxLength=128
	VersionKey string `json:"versionKey,omitempty"`

	// +kubebuilder:validation:MaxLength=128
	Description string `json:"description,omitempty"`

	// Checksum is what the file hashes to under the rule that decides what a
	// revision row records. It is what makes a plan refuse an artifact whose
	// bytes changed after the plan was published.
	// +kubebuilder:validation:MinLength=1
	// +kubebuilder:validation:MaxLength=128
	Checksum string `json:"checksum"`

	// Checkpoint marks a migration whose up body is the cumulative schema at
	// its version.
	Checkpoint bool `json:"checkpoint,omitempty"`

	// TransactionMode is the file's declared mode, resolved for this dialect:
	// "file", "none", or empty where the file declares none and the engine's
	// own mode decides. A run that stops halfway is read differently depending
	// on it, so the plan records what was true when it was made.
	// +kubebuilder:validation:Enum=file;none
	TransactionMode string `json:"transactionMode,omitempty"`
}

// PtahMigrationPlanSpec is generated by the controller and immutable
// thereafter.
//
// It is a separate kind from PtahSchemaPlan rather than a mode of it: a schema
// plan binds a fingerprint of the observed schema and one of the desired
// schema, and a migration plan binds a version sequence, per-migration
// checksums and the history it was computed against. One kind carrying both
// would make every field optional and dependent on which controller wrote it.
// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="a plan is immutable; generate a new plan instead"
type PtahMigrationPlanSpec struct {
	// ContractVersion versions plan publication separately from the Kubernetes
	// API version.
	// +kubebuilder:validation:Minimum=1
	// +kubebuilder:validation:Maximum=1
	ContractVersion int32 `json:"contractVersion"`

	MigrationRef ImmutableObjectReference `json:"migrationRef"`

	// Fingerprint binds this plan to everything that decided it. An approval
	// names it, and a changed input produces a different plan rather than a
	// changed one.
	// +kubebuilder:validation:MinLength=1
	// +kubebuilder:validation:MaxLength=128
	Fingerprint string `json:"fingerprint"`

	// Migrations is the exact sequence, in execution order, and the order is
	// the content: a plan that applies the same migrations in another order is
	// a different plan. So the list is atomic rather than a map keyed by
	// version -- a map declares the order insignificant, and it would also
	// require the version to be unique, which is the thing VersionKey exists
	// to say it is not.
	// +listType=atomic
	// +kubebuilder:validation:MinItems=1
	// +kubebuilder:validation:MaxItems=256
	Migrations []PlannedMigration `json:"migrations"`

	// HistoryFingerprint is the history this plan was computed against. A
	// history that changed between planning and execution invalidates the plan
	// rather than being applied to.
	// +kubebuilder:validation:MinLength=1
	// +kubebuilder:validation:MaxLength=128
	HistoryFingerprint string `json:"historyFingerprint"`

	// CurrentVersion is the version the history stood at when the plan was
	// made, published so an operator can read the plan's premise.
	// +kubebuilder:validation:Minimum=0
	CurrentVersion int64 `json:"currentVersion"`

	ArtifactDigest       string `json:"artifactDigest"`
	CoordinationDigest   string `json:"coordinationDigest"`
	TargetIdentityDigest string `json:"targetIdentityDigest"`
	PolicyFingerprint    string `json:"policyFingerprint"`

	VerificationPolicyUID    types.UID `json:"verificationPolicyUID"`
	VerificationPolicyDigest string    `json:"verificationPolicyDigest"`

	// ExecutionBindingID is a per-transition epoch. It changes even when an
	// operator rollout returns to byte-identical component versions.
	// +kubebuilder:validation:Pattern=`^v1-[0-9a-f]{32}$`
	ExecutionBindingID string `json:"executionBindingID"`
	// +kubebuilder:validation:Pattern=`^[^[:space:]@]+@sha256:[0-9a-f]{64}$`
	ControllerImage string `json:"controllerImage"`
	// +kubebuilder:validation:MinLength=1
	// +kubebuilder:validation:MaxLength=128
	// +kubebuilder:validation:Pattern=`^[^[:space:][:cntrl:]]([^[:cntrl:]]*[^[:space:][:cntrl:]])?$`
	ControllerRevision string `json:"controllerRevision"`
	// +kubebuilder:validation:Minimum=1
	ControllerStateVersion int32  `json:"controllerStateVersion"`
	PtahVersion            string `json:"ptahVersion"`
	ExecutorImage          string `json:"executorImage"`
	RunnerImage            string `json:"runnerImage"`
	// +kubebuilder:validation:Minimum=1
	RunnerProtocolVersion int32 `json:"runnerProtocolVersion"`

	CreatedAt metav1.Time `json:"createdAt"`
}

// PtahMigrationPlanStatus reports whether the plan is still the one the
// controller would publish today.
type PtahMigrationPlanStatus struct {
	ObservedGeneration int64 `json:"observedGeneration,omitempty"`
	// +listType=map
	// +listMapKey=type
	// +kubebuilder:validation:MaxItems=16
	Conditions []metav1.Condition `json:"conditions,omitempty"`
}

// Condition types a PtahMigrationPlan publishes.
const (
	// ConditionMigrationPlanCurrent reports that the plan still matches the
	// artifact and the history it was computed against.
	ConditionMigrationPlanCurrent = "Current"
	// ConditionMigrationPlanExecuted reports that the plan's sequence ran.
	ConditionMigrationPlanExecuted = "Executed"
)

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:resource:shortName=ptahmplan
// +kubebuilder:printcolumn:name="Migration",type=string,JSONPath=`.spec.migrationRef.name`
// +kubebuilder:printcolumn:name="From",type=integer,JSONPath=`.spec.currentVersion`
// +kubebuilder:printcolumn:name="Steps",type=integer,JSONPath=`.spec.migrations.length()`
// +kubebuilder:printcolumn:name="Current",type=string,JSONPath=`.status.conditions[?(@.type=='Current')].status`
// +kubebuilder:printcolumn:name="Age",type=date,JSONPath=`.metadata.creationTimestamp`
type PtahMigrationPlan struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   PtahMigrationPlanSpec   `json:"spec"`
	Status PtahMigrationPlanStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true
type PtahMigrationPlanList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []PtahMigrationPlan `json:"items"`
}
