package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/types"
)

// ImmutableObjectReference binds a name to the UID that existed when the
// reference was created, preventing delete-and-recreate aliasing.
type ImmutableObjectReference struct {
	Name string    `json:"name"`
	UID  types.UID `json:"uid"`
}

// PlanChunkReference identifies one ordered immutable ConfigMap chunk.
type PlanChunkReference struct {
	Name   string `json:"name"`
	Key    string `json:"key"`
	Index  int32  `json:"index"`
	Digest string `json:"digest"`
	Size   int32  `json:"size"`
}

// PtahSchemaPlanSpec is generated by the controller and immutable thereafter.
// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="a plan is immutable; generate a new plan instead"
type PtahSchemaPlanSpec struct {
	// ContractVersion versions plan publication and reconstruction separately
	// from the Kubernetes API version.
	// +kubebuilder:validation:Minimum=1
	ContractVersion int32 `json:"contractVersion"`

	SchemaRef ImmutableObjectReference `json:"schemaRef"`

	Fingerprint   string `json:"fingerprint"`
	ContentDigest string `json:"contentDigest"`
	Size          int64  `json:"size"`

	ArtifactDigest           string `json:"artifactDigest"`
	TargetIdentityDigest     string `json:"targetIdentityDigest"`
	ActualStateFingerprint   string `json:"actualStateFingerprint"`
	DesiredStateFingerprint  string `json:"desiredStateFingerprint"`
	PolicyFingerprint        string `json:"policyFingerprint"`
	VerificationPolicyDigest string `json:"verificationPolicyDigest"`
	PtahVersion              string `json:"ptahVersion"`
	ExecutorImage            string `json:"executorImage"`
	RunnerImage              string `json:"runnerImage"`
	RunnerProtocolVersion    int32  `json:"runnerProtocolVersion"`

	Dialect        string `json:"dialect"`
	Destructive    bool   `json:"destructive"`
	StatementCount int32  `json:"statementCount"`

	Chunks []PlanChunkReference `json:"chunks"`
}

// PtahSchemaPlanStatus is the commit record for non-transactional chunk
// publication. Approval and apply require Ready=True.
type PtahSchemaPlanStatus struct {
	ObservedGeneration int64                      `json:"observedGeneration,omitempty"`
	PublishedChunks    []PublishedPlanChunkStatus `json:"publishedChunks,omitempty"`
	Conditions         []metav1.Condition         `json:"conditions,omitempty"`
}

// PublishedPlanChunkStatus binds the immutable manifest to the concrete
// ConfigMap instances verified before Ready became true.
type PublishedPlanChunkStatus struct {
	Name  string    `json:"name"`
	UID   types.UID `json:"uid"`
	Index int32     `json:"index"`
}

const ConditionPlanStorageReady = "Ready"

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:resource:shortName=ptahplan
// +kubebuilder:printcolumn:name="Schema",type=string,JSONPath=`.spec.schemaRef.name`
// +kubebuilder:printcolumn:name="Fingerprint",type=string,JSONPath=`.spec.fingerprint`
// +kubebuilder:printcolumn:name="Statements",type=integer,JSONPath=`.spec.statementCount`
// +kubebuilder:printcolumn:name="Destructive",type=boolean,JSONPath=`.spec.destructive`
// +kubebuilder:printcolumn:name="Age",type=date,JSONPath=`.metadata.creationTimestamp`
type PtahSchemaPlan struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   PtahSchemaPlanSpec   `json:"spec,omitempty"`
	Status PtahSchemaPlanStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true
type PtahSchemaPlanList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []PtahSchemaPlan `json:"items"`
}
