//go:build !ignore_autogenerated

// Copyright 2026 The Ptah Operator Authors.
// SPDX-License-Identifier: MIT

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	corev1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/api/resource"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/types"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActiveOperationStatus) DeepCopyInto(out *ActiveOperationStatus) {
	*out = *in
	in.StartedAt.DeepCopyInto(&out.StartedAt)
	if in.AdmissionSnapshot != nil {
		in, out := &in.AdmissionSnapshot, &out.AdmissionSnapshot
		*out = new(PodAdmissionSnapshot)
		(*in).DeepCopyInto(*out)
	}
	if in.DispatchNotAfter != nil {
		in, out := &in.DispatchNotAfter, &out.DispatchNotAfter
		*out = (*in).DeepCopy()
	}
	if in.ExecutionNotAfter != nil {
		in, out := &in.ExecutionNotAfter, &out.ExecutionNotAfter
		*out = (*in).DeepCopy()
	}
	if in.Target != nil {
		in, out := &in.Target, &out.Target
		*out = new(DatabaseTargetBinding)
		(*in).DeepCopyInto(*out)
	}
	if in.ObservationExclude != nil {
		in, out := &in.ObservationExclude, &out.ObservationExclude
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ObservationDev != nil {
		in, out := &in.ObservationDev, &out.ObservationDev
		*out = new(DatabaseTargetRef)
		(*in).DeepCopyInto(*out)
	}
	out.ObservationConnectTimeout = in.ObservationConnectTimeout
	out.ObservationLockTimeout = in.ObservationLockTimeout
	if in.Source != nil {
		in, out := &in.Source, &out.Source
		*out = new(OCIArtifactAccessBinding)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActiveOperationStatus.
func (in *ActiveOperationStatus) DeepCopy() *ActiveOperationStatus {
	if in == nil {
		return nil
	}
	out := new(ActiveOperationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AdmissionObjectBinding) DeepCopyInto(out *AdmissionObjectBinding) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AdmissionObjectBinding.
func (in *AdmissionObjectBinding) DeepCopy() *AdmissionObjectBinding {
	if in == nil {
		return nil
	}
	out := new(AdmissionObjectBinding)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AppliedStatus) DeepCopyInto(out *AppliedStatus) {
	*out = *in
	if in.PlanRef != nil {
		in, out := &in.PlanRef, &out.PlanRef
		*out = new(ImmutableObjectReference)
		**out = **in
	}
	in.CompletedAt.DeepCopyInto(&out.CompletedAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AppliedStatus.
func (in *AppliedStatus) DeepCopy() *AppliedStatus {
	if in == nil {
		return nil
	}
	out := new(AppliedStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApprovalIdentity) DeepCopyInto(out *ApprovalIdentity) {
	*out = *in
	if in.Groups != nil {
		in, out := &in.Groups, &out.Groups
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApprovalIdentity.
func (in *ApprovalIdentity) DeepCopy() *ApprovalIdentity {
	if in == nil {
		return nil
	}
	out := new(ApprovalIdentity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConsumedApprovalStatus) DeepCopyInto(out *ConsumedApprovalStatus) {
	*out = *in
	in.Approver.DeepCopyInto(&out.Approver)
	in.ApprovedAt.DeepCopyInto(&out.ApprovedAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConsumedApprovalStatus.
func (in *ConsumedApprovalStatus) DeepCopy() *ConsumedApprovalStatus {
	if in == nil {
		return nil
	}
	out := new(ConsumedApprovalStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CurrentPlanStatus) DeepCopyInto(out *CurrentPlanStatus) {
	*out = *in
	in.CreatedAt.DeepCopyInto(&out.CreatedAt)
	if in.Approval != nil {
		in, out := &in.Approval, &out.Approval
		*out = new(ConsumedApprovalStatus)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CurrentPlanStatus.
func (in *CurrentPlanStatus) DeepCopy() *CurrentPlanStatus {
	if in == nil {
		return nil
	}
	out := new(CurrentPlanStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatabaseTargetBinding) DeepCopyInto(out *DatabaseTargetBinding) {
	*out = *in
	in.URLFrom.DeepCopyInto(&out.URLFrom)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatabaseTargetBinding.
func (in *DatabaseTargetBinding) DeepCopy() *DatabaseTargetBinding {
	if in == nil {
		return nil
	}
	out := new(DatabaseTargetBinding)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatabaseTargetRef) DeepCopyInto(out *DatabaseTargetRef) {
	*out = *in
	in.URLFrom.DeepCopyInto(&out.URLFrom)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatabaseTargetRef.
func (in *DatabaseTargetRef) DeepCopy() *DatabaseTargetRef {
	if in == nil {
		return nil
	}
	out := new(DatabaseTargetRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatabaseTargetSpec) DeepCopyInto(out *DatabaseTargetSpec) {
	*out = *in
	in.URLFrom.DeepCopyInto(&out.URLFrom)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatabaseTargetSpec.
func (in *DatabaseTargetSpec) DeepCopy() *DatabaseTargetSpec {
	if in == nil {
		return nil
	}
	out := new(DatabaseTargetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DriftFindingStatus) DeepCopyInto(out *DriftFindingStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DriftFindingStatus.
func (in *DriftFindingStatus) DeepCopy() *DriftFindingStatus {
	if in == nil {
		return nil
	}
	out := new(DriftFindingStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExecutionBindingStatus) DeepCopyInto(out *ExecutionBindingStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExecutionBindingStatus.
func (in *ExecutionBindingStatus) DeepCopy() *ExecutionBindingStatus {
	if in == nil {
		return nil
	}
	out := new(ExecutionBindingStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExecutionSpec) DeepCopyInto(out *ExecutionSpec) {
	*out = *in
	out.FailureRetryInterval = in.FailureRetryInterval
	out.ConnectTimeout = in.ConnectTimeout
	in.Resources.DeepCopyInto(&out.Resources)
	if in.ImagePullSecrets != nil {
		in, out := &in.ImagePullSecrets, &out.ImagePullSecrets
		*out = make([]corev1.LocalObjectReference, len(*in))
		copy(*out, *in)
	}
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]corev1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Affinity != nil {
		in, out := &in.Affinity, &out.Affinity
		*out = new(corev1.Affinity)
		(*in).DeepCopyInto(*out)
	}
	if in.RuntimeClassName != nil {
		in, out := &in.RuntimeClassName, &out.RuntimeClassName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExecutionSpec.
func (in *ExecutionSpec) DeepCopy() *ExecutionSpec {
	if in == nil {
		return nil
	}
	out := new(ExecutionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImmutableObjectReference) DeepCopyInto(out *ImmutableObjectReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImmutableObjectReference.
func (in *ImmutableObjectReference) DeepCopy() *ImmutableObjectReference {
	if in == nil {
		return nil
	}
	out := new(ImmutableObjectReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LimitRangeAdmissionSnapshot) DeepCopyInto(out *LimitRangeAdmissionSnapshot) {
	*out = *in
	out.Object = in.Object
	if in.DefaultRequests != nil {
		in, out := &in.DefaultRequests, &out.DefaultRequests
		*out = make(map[corev1.ResourceName]resource.Quantity, len(*in))
		for key, val := range *in {
			(*out)[key] = val.DeepCopy()
		}
	}
	if in.DefaultLimits != nil {
		in, out := &in.DefaultLimits, &out.DefaultLimits
		*out = make(map[corev1.ResourceName]resource.Quantity, len(*in))
		for key, val := range *in {
			(*out)[key] = val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LimitRangeAdmissionSnapshot.
func (in *LimitRangeAdmissionSnapshot) DeepCopy() *LimitRangeAdmissionSnapshot {
	if in == nil {
		return nil
	}
	out := new(LimitRangeAdmissionSnapshot)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MigrationHistoryStatus) DeepCopyInto(out *MigrationHistoryStatus) {
	*out = *in
	in.ObservedAt.DeepCopyInto(&out.ObservedAt)
	if in.ModifiedVersions != nil {
		in, out := &in.ModifiedVersions, &out.ModifiedVersions
		*out = make([]int64, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MigrationHistoryStatus.
func (in *MigrationHistoryStatus) DeepCopy() *MigrationHistoryStatus {
	if in == nil {
		return nil
	}
	out := new(MigrationHistoryStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MigrationPolicy) DeepCopyInto(out *MigrationPolicy) {
	*out = *in
	out.LockTimeout = in.LockTimeout
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MigrationPolicy.
func (in *MigrationPolicy) DeepCopy() *MigrationPolicy {
	if in == nil {
		return nil
	}
	out := new(MigrationPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MigrationRunStatus) DeepCopyInto(out *MigrationRunStatus) {
	*out = *in
	in.StartedAt.DeepCopyInto(&out.StartedAt)
	if in.FinishedAt != nil {
		in, out := &in.FinishedAt, &out.FinishedAt
		*out = (*in).DeepCopy()
	}
	if in.AppliedVersions != nil {
		in, out := &in.AppliedVersions, &out.AppliedVersions
		*out = make([]int64, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MigrationRunStatus.
func (in *MigrationRunStatus) DeepCopy() *MigrationRunStatus {
	if in == nil {
		return nil
	}
	out := new(MigrationRunStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OCIArtifactAccessBinding) DeepCopyInto(out *OCIArtifactAccessBinding) {
	*out = *in
	if in.RegistryAuthFrom != nil {
		in, out := &in.RegistryAuthFrom, &out.RegistryAuthFrom
		*out = new(RegistryAuthSource)
		**out = **in
	}
	in.Transport.DeepCopyInto(&out.Transport)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OCIArtifactAccessBinding.
func (in *OCIArtifactAccessBinding) DeepCopy() *OCIArtifactAccessBinding {
	if in == nil {
		return nil
	}
	out := new(OCIArtifactAccessBinding)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OCIArtifactSourceSpec) DeepCopyInto(out *OCIArtifactSourceSpec) {
	*out = *in
	if in.RegistryAuthFrom != nil {
		in, out := &in.RegistryAuthFrom, &out.RegistryAuthFrom
		*out = new(RegistryAuthSource)
		**out = **in
	}
	in.VerificationPolicyFrom.DeepCopyInto(&out.VerificationPolicyFrom)
	in.Transport.DeepCopyInto(&out.Transport)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OCIArtifactSourceSpec.
func (in *OCIArtifactSourceSpec) DeepCopy() *OCIArtifactSourceSpec {
	if in == nil {
		return nil
	}
	out := new(OCIArtifactSourceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OCITransportSpec) DeepCopyInto(out *OCITransportSpec) {
	*out = *in
	if in.CAFrom != nil {
		in, out := &in.CAFrom, &out.CAFrom
		*out = new(corev1.ConfigMapKeySelector)
		(*in).DeepCopyInto(*out)
	}
	if in.ClientCertificateFrom != nil {
		in, out := &in.ClientCertificateFrom, &out.ClientCertificateFrom
		*out = new(TLSSecretReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OCITransportSpec.
func (in *OCITransportSpec) DeepCopy() *OCITransportSpec {
	if in == nil {
		return nil
	}
	out := new(OCITransportSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PendingObservationStatus) DeepCopyInto(out *PendingObservationStatus) {
	*out = *in
	if in.AdmissionSnapshot != nil {
		in, out := &in.AdmissionSnapshot, &out.AdmissionSnapshot
		*out = new(PodAdmissionSnapshot)
		(*in).DeepCopyInto(*out)
	}
	if in.ApplyPodUIDs != nil {
		in, out := &in.ApplyPodUIDs, &out.ApplyPodUIDs
		*out = make([]types.UID, len(*in))
		copy(*out, *in)
	}
	if in.ObserveAfter != nil {
		in, out := &in.ObserveAfter, &out.ObserveAfter
		*out = (*in).DeepCopy()
	}
	in.Plan.DeepCopyInto(&out.Plan)
	in.Target.DeepCopyInto(&out.Target)
	in.Source.DeepCopyInto(&out.Source)
	if in.Dev != nil {
		in, out := &in.Dev, &out.Dev
		*out = new(DatabaseTargetRef)
		(*in).DeepCopyInto(*out)
	}
	if in.Exclude != nil {
		in, out := &in.Exclude, &out.Exclude
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	out.ConnectTimeout = in.ConnectTimeout
	out.LockTimeout = in.LockTimeout
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PendingObservationStatus.
func (in *PendingObservationStatus) DeepCopy() *PendingObservationStatus {
	if in == nil {
		return nil
	}
	out := new(PendingObservationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlanChunkReference) DeepCopyInto(out *PlanChunkReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlanChunkReference.
func (in *PlanChunkReference) DeepCopy() *PlanChunkReference {
	if in == nil {
		return nil
	}
	out := new(PlanChunkReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlannedMigration) DeepCopyInto(out *PlannedMigration) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlannedMigration.
func (in *PlannedMigration) DeepCopy() *PlannedMigration {
	if in == nil {
		return nil
	}
	out := new(PlannedMigration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodAdmissionSnapshot) DeepCopyInto(out *PodAdmissionSnapshot) {
	*out = *in
	in.ServiceAccount.DeepCopyInto(&out.ServiceAccount)
	if in.LimitRanges != nil {
		in, out := &in.LimitRanges, &out.LimitRanges
		*out = make([]LimitRangeAdmissionSnapshot, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.RuntimeClass != nil {
		in, out := &in.RuntimeClass, &out.RuntimeClass
		*out = new(RuntimeClassAdmissionSnapshot)
		(*in).DeepCopyInto(*out)
	}
	in.PriorityClass.DeepCopyInto(&out.PriorityClass)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodAdmissionSnapshot.
func (in *PodAdmissionSnapshot) DeepCopy() *PodAdmissionSnapshot {
	if in == nil {
		return nil
	}
	out := new(PodAdmissionSnapshot)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PriorityClassAdmissionSnapshot) DeepCopyInto(out *PriorityClassAdmissionSnapshot) {
	*out = *in
	if in.Object != nil {
		in, out := &in.Object, &out.Object
		*out = new(AdmissionObjectBinding)
		**out = **in
	}
	if in.PreemptionPolicy != nil {
		in, out := &in.PreemptionPolicy, &out.PreemptionPolicy
		*out = new(corev1.PreemptionPolicy)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PriorityClassAdmissionSnapshot.
func (in *PriorityClassAdmissionSnapshot) DeepCopy() *PriorityClassAdmissionSnapshot {
	if in == nil {
		return nil
	}
	out := new(PriorityClassAdmissionSnapshot)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PtahMigration) DeepCopyInto(out *PtahMigration) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PtahMigration.
func (in *PtahMigration) DeepCopy() *PtahMigration {
	if in == nil {
		return nil
	}
	out := new(PtahMigration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PtahMigration) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PtahMigrationApproval) DeepCopyInto(out *PtahMigrationApproval) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PtahMigrationApproval.
func (in *PtahMigrationApproval) DeepCopy() *PtahMigrationApproval {
	if in == nil {
		return nil
	}
	out := new(PtahMigrationApproval)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PtahMigrationApproval) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PtahMigrationApprovalList) DeepCopyInto(out *PtahMigrationApprovalList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PtahMigrationApproval, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PtahMigrationApprovalList.
func (in *PtahMigrationApprovalList) DeepCopy() *PtahMigrationApprovalList {
	if in == nil {
		return nil
	}
	out := new(PtahMigrationApprovalList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PtahMigrationApprovalList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PtahMigrationApprovalSpec) DeepCopyInto(out *PtahMigrationApprovalSpec) {
	*out = *in
	out.MigrationRef = in.MigrationRef
	out.PlanRef = in.PlanRef
	in.Approver.DeepCopyInto(&out.Approver)
	in.ApprovedAt.DeepCopyInto(&out.ApprovedAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PtahMigrationApprovalSpec.
func (in *PtahMigrationApprovalSpec) DeepCopy() *PtahMigrationApprovalSpec {
	if in == nil {
		return nil
	}
	out := new(PtahMigrationApprovalSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PtahMigrationApprovalStatus) DeepCopyInto(out *PtahMigrationApprovalStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PtahMigrationApprovalStatus.
func (in *PtahMigrationApprovalStatus) DeepCopy() *PtahMigrationApprovalStatus {
	if in == nil {
		return nil
	}
	out := new(PtahMigrationApprovalStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PtahMigrationList) DeepCopyInto(out *PtahMigrationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PtahMigration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PtahMigrationList.
func (in *PtahMigrationList) DeepCopy() *PtahMigrationList {
	if in == nil {
		return nil
	}
	out := new(PtahMigrationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PtahMigrationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PtahMigrationPlan) DeepCopyInto(out *PtahMigrationPlan) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PtahMigrationPlan.
func (in *PtahMigrationPlan) DeepCopy() *PtahMigrationPlan {
	if in == nil {
		return nil
	}
	out := new(PtahMigrationPlan)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PtahMigrationPlan) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PtahMigrationPlanList) DeepCopyInto(out *PtahMigrationPlanList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PtahMigrationPlan, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PtahMigrationPlanList.
func (in *PtahMigrationPlanList) DeepCopy() *PtahMigrationPlanList {
	if in == nil {
		return nil
	}
	out := new(PtahMigrationPlanList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PtahMigrationPlanList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PtahMigrationPlanSpec) DeepCopyInto(out *PtahMigrationPlanSpec) {
	*out = *in
	out.MigrationRef = in.MigrationRef
	if in.Migrations != nil {
		in, out := &in.Migrations, &out.Migrations
		*out = make([]PlannedMigration, len(*in))
		copy(*out, *in)
	}
	in.CreatedAt.DeepCopyInto(&out.CreatedAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PtahMigrationPlanSpec.
func (in *PtahMigrationPlanSpec) DeepCopy() *PtahMigrationPlanSpec {
	if in == nil {
		return nil
	}
	out := new(PtahMigrationPlanSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PtahMigrationPlanStatus) DeepCopyInto(out *PtahMigrationPlanStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PtahMigrationPlanStatus.
func (in *PtahMigrationPlanStatus) DeepCopy() *PtahMigrationPlanStatus {
	if in == nil {
		return nil
	}
	out := new(PtahMigrationPlanStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PtahMigrationSpec) DeepCopyInto(out *PtahMigrationSpec) {
	*out = *in
	in.Target.DeepCopyInto(&out.Target)
	in.Artifact.DeepCopyInto(&out.Artifact)
	out.Policy = in.Policy
	out.Interval = in.Interval
	in.Execution.DeepCopyInto(&out.Execution)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PtahMigrationSpec.
func (in *PtahMigrationSpec) DeepCopy() *PtahMigrationSpec {
	if in == nil {
		return nil
	}
	out := new(PtahMigrationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PtahMigrationStatus) DeepCopyInto(out *PtahMigrationStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Artifact != nil {
		in, out := &in.Artifact, &out.Artifact
		*out = new(OCIArtifactAccessBinding)
		(*in).DeepCopyInto(*out)
	}
	if in.ExecutionBinding != nil {
		in, out := &in.ExecutionBinding, &out.ExecutionBinding
		*out = new(ExecutionBindingStatus)
		**out = **in
	}
	if in.History != nil {
		in, out := &in.History, &out.History
		*out = new(MigrationHistoryStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Plan != nil {
		in, out := &in.Plan, &out.Plan
		*out = new(ImmutableObjectReference)
		**out = **in
	}
	if in.LastRun != nil {
		in, out := &in.LastRun, &out.LastRun
		*out = new(MigrationRunStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.NextReconciliationTime != nil {
		in, out := &in.NextReconciliationTime, &out.NextReconciliationTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PtahMigrationStatus.
func (in *PtahMigrationStatus) DeepCopy() *PtahMigrationStatus {
	if in == nil {
		return nil
	}
	out := new(PtahMigrationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PtahSchema) DeepCopyInto(out *PtahSchema) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PtahSchema.
func (in *PtahSchema) DeepCopy() *PtahSchema {
	if in == nil {
		return nil
	}
	out := new(PtahSchema)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PtahSchema) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PtahSchemaApproval) DeepCopyInto(out *PtahSchemaApproval) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PtahSchemaApproval.
func (in *PtahSchemaApproval) DeepCopy() *PtahSchemaApproval {
	if in == nil {
		return nil
	}
	out := new(PtahSchemaApproval)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PtahSchemaApproval) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PtahSchemaApprovalList) DeepCopyInto(out *PtahSchemaApprovalList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PtahSchemaApproval, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PtahSchemaApprovalList.
func (in *PtahSchemaApprovalList) DeepCopy() *PtahSchemaApprovalList {
	if in == nil {
		return nil
	}
	out := new(PtahSchemaApprovalList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PtahSchemaApprovalList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PtahSchemaApprovalSpec) DeepCopyInto(out *PtahSchemaApprovalSpec) {
	*out = *in
	out.SchemaRef = in.SchemaRef
	out.PlanRef = in.PlanRef
	in.Approver.DeepCopyInto(&out.Approver)
	in.ApprovedAt.DeepCopyInto(&out.ApprovedAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PtahSchemaApprovalSpec.
func (in *PtahSchemaApprovalSpec) DeepCopy() *PtahSchemaApprovalSpec {
	if in == nil {
		return nil
	}
	out := new(PtahSchemaApprovalSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PtahSchemaApprovalStatus) DeepCopyInto(out *PtahSchemaApprovalStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PtahSchemaApprovalStatus.
func (in *PtahSchemaApprovalStatus) DeepCopy() *PtahSchemaApprovalStatus {
	if in == nil {
		return nil
	}
	out := new(PtahSchemaApprovalStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PtahSchemaList) DeepCopyInto(out *PtahSchemaList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PtahSchema, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PtahSchemaList.
func (in *PtahSchemaList) DeepCopy() *PtahSchemaList {
	if in == nil {
		return nil
	}
	out := new(PtahSchemaList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PtahSchemaList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PtahSchemaPlan) DeepCopyInto(out *PtahSchemaPlan) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PtahSchemaPlan.
func (in *PtahSchemaPlan) DeepCopy() *PtahSchemaPlan {
	if in == nil {
		return nil
	}
	out := new(PtahSchemaPlan)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PtahSchemaPlan) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PtahSchemaPlanList) DeepCopyInto(out *PtahSchemaPlanList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PtahSchemaPlan, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PtahSchemaPlanList.
func (in *PtahSchemaPlanList) DeepCopy() *PtahSchemaPlanList {
	if in == nil {
		return nil
	}
	out := new(PtahSchemaPlanList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PtahSchemaPlanList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PtahSchemaPlanSpec) DeepCopyInto(out *PtahSchemaPlanSpec) {
	*out = *in
	out.SchemaRef = in.SchemaRef
	if in.Chunks != nil {
		in, out := &in.Chunks, &out.Chunks
		*out = make([]PlanChunkReference, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PtahSchemaPlanSpec.
func (in *PtahSchemaPlanSpec) DeepCopy() *PtahSchemaPlanSpec {
	if in == nil {
		return nil
	}
	out := new(PtahSchemaPlanSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PtahSchemaPlanStatus) DeepCopyInto(out *PtahSchemaPlanStatus) {
	*out = *in
	if in.PublishedChunks != nil {
		in, out := &in.PublishedChunks, &out.PublishedChunks
		*out = make([]PublishedPlanChunkStatus, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PtahSchemaPlanStatus.
func (in *PtahSchemaPlanStatus) DeepCopy() *PtahSchemaPlanStatus {
	if in == nil {
		return nil
	}
	out := new(PtahSchemaPlanStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PtahSchemaSpec) DeepCopyInto(out *PtahSchemaSpec) {
	*out = *in
	in.Target.DeepCopyInto(&out.Target)
	in.Desired.DeepCopyInto(&out.Desired)
	if in.Dev != nil {
		in, out := &in.Dev, &out.Dev
		*out = new(DatabaseTargetRef)
		(*in).DeepCopyInto(*out)
	}
	in.Policy.DeepCopyInto(&out.Policy)
	out.Interval = in.Interval
	in.Execution.DeepCopyInto(&out.Execution)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PtahSchemaSpec.
func (in *PtahSchemaSpec) DeepCopy() *PtahSchemaSpec {
	if in == nil {
		return nil
	}
	out := new(PtahSchemaSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PtahSchemaStatus) DeepCopyInto(out *PtahSchemaStatus) {
	*out = *in
	if in.ExecutionBinding != nil {
		in, out := &in.ExecutionBinding, &out.ExecutionBinding
		*out = new(ExecutionBindingStatus)
		**out = **in
	}
	in.Source.DeepCopyInto(&out.Source)
	in.Target.DeepCopyInto(&out.Target)
	if in.Plan != nil {
		in, out := &in.Plan, &out.Plan
		*out = new(CurrentPlanStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Applied != nil {
		in, out := &in.Applied, &out.Applied
		*out = new(AppliedStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.PendingObservation != nil {
		in, out := &in.PendingObservation, &out.PendingObservation
		*out = new(PendingObservationStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.PendingLockRelease != nil {
		in, out := &in.PendingLockRelease, &out.PendingLockRelease
		*out = new(TargetLockReleaseStatus)
		**out = **in
	}
	if in.ActiveOperation != nil {
		in, out := &in.ActiveOperation, &out.ActiveOperation
		*out = new(ActiveOperationStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.LastAttemptTime != nil {
		in, out := &in.LastAttemptTime, &out.LastAttemptTime
		*out = (*in).DeepCopy()
	}
	if in.LastSuccessfulReconciliation != nil {
		in, out := &in.LastSuccessfulReconciliation, &out.LastSuccessfulReconciliation
		*out = (*in).DeepCopy()
	}
	if in.NextReconciliationTime != nil {
		in, out := &in.NextReconciliationTime, &out.NextReconciliationTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PtahSchemaStatus.
func (in *PtahSchemaStatus) DeepCopy() *PtahSchemaStatus {
	if in == nil {
		return nil
	}
	out := new(PtahSchemaStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PublishedPlanChunkStatus) DeepCopyInto(out *PublishedPlanChunkStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PublishedPlanChunkStatus.
func (in *PublishedPlanChunkStatus) DeepCopy() *PublishedPlanChunkStatus {
	if in == nil {
		return nil
	}
	out := new(PublishedPlanChunkStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReconciliationPolicy) DeepCopyInto(out *ReconciliationPolicy) {
	*out = *in
	if in.Exclude != nil {
		in, out := &in.Exclude, &out.Exclude
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	out.LockTimeout = in.LockTimeout
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReconciliationPolicy.
func (in *ReconciliationPolicy) DeepCopy() *ReconciliationPolicy {
	if in == nil {
		return nil
	}
	out := new(ReconciliationPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RegistryAuthSource) DeepCopyInto(out *RegistryAuthSource) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RegistryAuthSource.
func (in *RegistryAuthSource) DeepCopy() *RegistryAuthSource {
	if in == nil {
		return nil
	}
	out := new(RegistryAuthSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RuntimeClassAdmissionSnapshot) DeepCopyInto(out *RuntimeClassAdmissionSnapshot) {
	*out = *in
	out.Object = in.Object
	if in.Overhead != nil {
		in, out := &in.Overhead, &out.Overhead
		*out = make(map[corev1.ResourceName]resource.Quantity, len(*in))
		for key, val := range *in {
			(*out)[key] = val.DeepCopy()
		}
	}
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]corev1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RuntimeClassAdmissionSnapshot.
func (in *RuntimeClassAdmissionSnapshot) DeepCopy() *RuntimeClassAdmissionSnapshot {
	if in == nil {
		return nil
	}
	out := new(RuntimeClassAdmissionSnapshot)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SchemaSourceStatus) DeepCopyInto(out *SchemaSourceStatus) {
	*out = *in
	if in.ResolvedAt != nil {
		in, out := &in.ResolvedAt, &out.ResolvedAt
		*out = (*in).DeepCopy()
	}
	if in.VerifiedAt != nil {
		in, out := &in.VerifiedAt, &out.VerifiedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SchemaSourceStatus.
func (in *SchemaSourceStatus) DeepCopy() *SchemaSourceStatus {
	if in == nil {
		return nil
	}
	out := new(SchemaSourceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceAccountAdmissionSnapshot) DeepCopyInto(out *ServiceAccountAdmissionSnapshot) {
	*out = *in
	out.Object = in.Object
	if in.ImagePullSecrets != nil {
		in, out := &in.ImagePullSecrets, &out.ImagePullSecrets
		*out = make([]corev1.LocalObjectReference, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceAccountAdmissionSnapshot.
func (in *ServiceAccountAdmissionSnapshot) DeepCopy() *ServiceAccountAdmissionSnapshot {
	if in == nil {
		return nil
	}
	out := new(ServiceAccountAdmissionSnapshot)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TLSSecretReference) DeepCopyInto(out *TLSSecretReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TLSSecretReference.
func (in *TLSSecretReference) DeepCopy() *TLSSecretReference {
	if in == nil {
		return nil
	}
	out := new(TLSSecretReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TargetLockReleaseStatus) DeepCopyInto(out *TargetLockReleaseStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TargetLockReleaseStatus.
func (in *TargetLockReleaseStatus) DeepCopy() *TargetLockReleaseStatus {
	if in == nil {
		return nil
	}
	out := new(TargetLockReleaseStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TargetStatus) DeepCopyInto(out *TargetStatus) {
	*out = *in
	if in.LastObservedAt != nil {
		in, out := &in.LastObservedAt, &out.LastObservedAt
		*out = (*in).DeepCopy()
	}
	if in.DriftFindings != nil {
		in, out := &in.DriftFindings, &out.DriftFindings
		*out = make([]DriftFindingStatus, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TargetStatus.
func (in *TargetStatus) DeepCopy() *TargetStatus {
	if in == nil {
		return nil
	}
	out := new(TargetStatus)
	in.DeepCopyInto(out)
	return out
}
