package main

import (
	"strings"
	"testing"

	admissionregistrationv1 "k8s.io/api/admissionregistration/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// sample is a small template every mutation below starts from: one policy
// with a parameter used each of the three ways the emitter writes one, and
// its binding.
func sample() template {
	fail := admissionregistrationv1.Fail
	exact := admissionregistrationv1.Exact
	scope := admissionregistrationv1.NamespacedScope
	policy := &admissionregistrationv1.ValidatingAdmissionPolicy{
		TypeMeta:   metav1.TypeMeta{APIVersion: "admissionregistration.k8s.io/v1", Kind: "ValidatingAdmissionPolicy"},
		ObjectMeta: metav1.ObjectMeta{Name: "__NAME__", Labels: map[string]string{"app.kubernetes.io/component": "sample"}},
		Spec: admissionregistrationv1.ValidatingAdmissionPolicySpec{
			FailurePolicy: &fail,
			MatchConstraints: &admissionregistrationv1.MatchResources{
				MatchPolicy:       &exact,
				NamespaceSelector: &metav1.LabelSelector{},
				ObjectSelector:    &metav1.LabelSelector{},
				ResourceRules: []admissionregistrationv1.NamedRuleWithOperations{{
					RuleWithOperations: admissionregistrationv1.RuleWithOperations{
						Operations: []admissionregistrationv1.OperationType{admissionregistrationv1.Create, admissionregistrationv1.Update},
						Rule: admissionregistrationv1.Rule{
							APIGroups: []string{""}, APIVersions: []string{"v1"}, Resources: []string{"configmaps"}, Scope: &scope,
						},
					},
				}},
			},
			MatchConditions: []admissionregistrationv1.MatchCondition{{
				Name:       "caller",
				Expression: `request.userInfo.username == "system:serviceaccount:__NS__:__SA__"`,
			}},
			Variables: []admissionregistrationv1.Variable{
				{Name: "image", Expression: `"__IMAGE__"`},
				{Name: "namespace", Expression: `__NS__`},
				{Name: "percent", Expression: `__IMAGE__ at 100%`},
			},
			Validations: []admissionregistrationv1.Validation{
				{Expression: `object.metadata.labels["a"] == "b" && object.metadata.name.matches("^x-[0-9]{3}$")`, Message: "refused"},
				{Expression: `size(object.data) == 0`, Message: "refused"},
			},
		},
	}
	binding := &admissionregistrationv1.ValidatingAdmissionPolicyBinding{
		TypeMeta:   metav1.TypeMeta{APIVersion: "admissionregistration.k8s.io/v1", Kind: "ValidatingAdmissionPolicyBinding"},
		ObjectMeta: metav1.ObjectMeta{Name: "__NAME__", Labels: map[string]string{"app.kubernetes.io/component": "sample"}},
		Spec: admissionregistrationv1.ValidatingAdmissionPolicyBindingSpec{
			PolicyName:        "__NAME__",
			ValidationActions: []admissionregistrationv1.ValidationAction{admissionregistrationv1.Deny},
			MatchResources: &admissionregistrationv1.MatchResources{
				NamespaceSelector: &metav1.LabelSelector{MatchLabels: map[string]string{"kubernetes.io/metadata.name": "__NS__"}},
			},
		},
	}
	return template{
		path:     "templates/sample.yaml",
		source:   "sample.go",
		preamble: []string{`$image := include "sample.image" .`},
		parameters: []parameter{
			{"__NAME__", `include "sample.name" .`},
			{"__NS__", ".Release.Namespace"},
			{"__SA__", "$serviceAccount"},
			{"__IMAGE__", "$image"},
		},
		pairs: []policyPair{{policy: policy, binding: binding}},
	}
}

// TestEmitWritesEachParameterForm pins how a parameter reaches the template:
// bare where it is a name, quoted where it is the whole of an expression,
// printf "%q" where the Go definition quoted it, and printf with the rest of
// the string where it is embedded, with any percent sign escaped.
func TestEmitWritesEachParameterForm(t *testing.T) {
	t.Parallel()

	out, err := emit(sample())
	if err != nil {
		t.Fatal(err)
	}
	for _, want := range []string{
		"Generated by hack/chartpolicies from sample.go.",
		"{{- $image := include \"sample.image\" . -}}\n",
		"  name: {{ include \"sample.name\" . }}\n",
		"  policyName: {{ include \"sample.name\" . }}\n",
		"    {{- include \"ptah-operator.labels\" . | nindent 4 }}\n    app.kubernetes.io/component: sample\n",
		"      expression: {{ printf `request.userInfo.username == \"system:serviceaccount:%s:%s\"` .Release.Namespace $serviceAccount | quote }}\n",
		"    - name: image\n      expression: {{ printf \"%q\" $image | quote }}\n",
		"    - name: namespace\n      expression: {{ .Release.Namespace | quote }}\n",
		"    - name: percent\n      expression: {{ printf `%s at 100%%` $image | quote }}\n",
		"    - expression: {{ `object.metadata.labels[\"a\"] == \"b\" && object.metadata.name.matches(\"^x-[0-9]{3}$\")` | quote }}\n      message: \"refused\"\n",
		"    - expression: \"size(object.data) == 0\"\n",
		"        operations: [\"CREATE\", \"UPDATE\"]\n",
		"      - apiGroups: [\"\"]\n",
		"        kubernetes.io/metadata.name: {{ .Release.Namespace }}\n",
		"  validationActions: [Deny]\n",
	} {
		if !strings.Contains(out, want) {
			t.Errorf("emitted template lacks %q:\n%s", want, out)
		}
	}
	if strings.Contains(out, "__") {
		t.Errorf("a sentinel reached the template:\n%s", out)
	}
}

// TestEmitWritesTheConditionAroundTheWholeFile pins the shape of a template
// that renders only under a value.
func TestEmitWritesTheConditionAroundTheWholeFile(t *testing.T) {
	t.Parallel()

	tmpl := sample()
	tmpl.condition = ".Values.sample.enabled"
	out, err := emit(tmpl)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(out, "*/ -}}\n{{- if .Values.sample.enabled }}\n{{- $image") || !strings.HasSuffix(out, "  validationActions: [Deny]\n{{- end }}\n") {
		t.Fatalf("the condition does not wrap the file:\n%s", out)
	}
}

// TestEmitRefusesWhatItCannotWriteFaithfully hands the emitter definitions it
// must refuse: a field it does not write, a value it cannot spell, a
// parameter it has no expression for. Each would otherwise become a template
// that silently says less than the Go definition.
func TestEmitRefusesWhatItCannotWriteFaithfully(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name   string
		mutate func(*template)
		want   string
	}{
		{
			name:   "a parameter the template has no expression for",
			mutate: func(tmpl *template) { tmpl.parameters = tmpl.parameters[:3] },
			want:   "reached the template unsubstituted",
		},
		{
			name: "paramKind",
			mutate: func(tmpl *template) {
				tmpl.pairs[0].policy.Spec.ParamKind = &admissionregistrationv1.ParamKind{Kind: "ConfigMap"}
			},
			want: "paramKind is not supported",
		},
		{
			name: "paramRef",
			mutate: func(tmpl *template) {
				tmpl.pairs[0].binding.Spec.ParamRef = &admissionregistrationv1.ParamRef{Name: "params"}
			},
			want: "paramRef is not supported",
		},
		{
			name: "auditAnnotations",
			mutate: func(tmpl *template) {
				tmpl.pairs[0].policy.Spec.AuditAnnotations = []admissionregistrationv1.AuditAnnotation{{Key: "k", ValueExpression: "'v'"}}
			},
			want: "auditAnnotations are not supported",
		},
		{
			name:   "an implicit failure policy",
			mutate: func(tmpl *template) { tmpl.pairs[0].policy.Spec.FailurePolicy = nil },
			want:   "failurePolicy must be explicit",
		},
		{
			name: "a selector with expressions",
			mutate: func(tmpl *template) {
				tmpl.pairs[0].policy.Spec.MatchConstraints.NamespaceSelector.MatchExpressions = []metav1.LabelSelectorRequirement{{
					Key: "team", Operator: metav1.LabelSelectorOpExists,
				}}
			},
			want: "matchExpressions are not supported",
		},
		{
			name: "resource names",
			mutate: func(tmpl *template) {
				tmpl.pairs[0].policy.Spec.MatchConstraints.ResourceRules[0].ResourceNames = []string{"one"}
			},
			want: "resourceNames are not supported",
		},
		{
			name: "an implicit scope",
			mutate: func(tmpl *template) {
				tmpl.pairs[0].policy.Spec.MatchConstraints.ResourceRules[0].Scope = nil
			},
			want: "scope must be explicit",
		},
		{
			name: "a parameter inside a rule",
			mutate: func(tmpl *template) {
				tmpl.pairs[0].policy.Spec.MatchConstraints.ResourceRules[0].Resources = []string{"__NS__"}
			},
			want: "carries a parameter",
		},
		{
			name: "a backtick in an expression",
			mutate: func(tmpl *template) {
				tmpl.pairs[0].policy.Spec.Validations[1].Expression = "object.data[\"x\"] == \"`\""
			},
			want: "holds a backtick",
		},
		{
			name: "a backtick beside a parameter",
			mutate: func(tmpl *template) {
				tmpl.pairs[0].policy.Spec.Validations[1].Expression = "object.data[\"x\"] == \"`__NS__\""
			},
			want: "holds a backtick",
		},
		{
			name: "a release label on the object",
			mutate: func(tmpl *template) {
				tmpl.pairs[0].policy.Labels["app.kubernetes.io/managed-by"] = "Helm"
			},
			want: "already writes",
		},
		{
			name:   "metadata beyond a name and labels",
			mutate: func(tmpl *template) { tmpl.pairs[0].binding.Annotations = map[string]string{"a": "b"} },
			want:   "more than a name and labels",
		},
		{
			name:   "a name that is not a bare scalar",
			mutate: func(tmpl *template) { tmpl.pairs[0].policy.Spec.MatchConditions[0].Name = "has space" },
			want:   "cannot be written as a bare scalar",
		},
		{
			name:   "the wrong kind",
			mutate: func(tmpl *template) { tmpl.pairs[0].policy.Kind = "ValidatingWebhookConfiguration" },
			want:   "typeMeta is",
		},
		{
			name:   "no validations",
			mutate: func(tmpl *template) { tmpl.pairs[0].policy.Spec.Validations = nil },
			want:   "no validations",
		},
		{
			name:   "no policies",
			mutate: func(tmpl *template) { tmpl.pairs = nil },
			want:   "no policies",
		},
	}
	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			t.Parallel()
			tmpl := sample()
			test.mutate(&tmpl)
			out, err := emit(tmpl)
			if err == nil {
				t.Fatalf("emit accepted the definition:\n%s", out)
			}
			if !strings.Contains(err.Error(), test.want) {
				t.Fatalf("emit refused with %q, want a refusal naming %q", err, test.want)
			}
		})
	}
}
