package main

import (
	"errors"
	"fmt"
	"regexp"
	"slices"
	"sort"
	"strconv"
	"strings"

	admissionregistrationv1 "k8s.io/api/admissionregistration/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// A parameter is a value the chart decides when it renders. The Go
// definition is built with sentinel in the value's place, and the emitter
// writes helm, a Helm expression, wherever the sentinel appears: on its own,
// as the whole of a Go-quoted literal, or inside a longer string, which
// becomes a printf.
type parameter struct {
	sentinel string
	helm     string
}

// policyPair is one policy with the binding that enforces it.
type policyPair struct {
	policy  *admissionregistrationv1.ValidatingAdmissionPolicy
	binding *admissionregistrationv1.ValidatingAdmissionPolicyBinding
}

// template is one generated chart template.
type template struct {
	// path is the template's path inside the chart.
	path string
	// source is the Go file the policies are defined in, named in the
	// header so a reader of the template knows what to edit instead.
	source string
	// condition, when set, is the Helm expression the whole file renders
	// under; a false condition renders nothing.
	condition string
	// preamble are the template's own variable definitions, written
	// verbatim after the header. A parameter's Helm expression may name one.
	preamble   []string
	parameters []parameter
	pairs      []policyPair
}

// releaseLabels are what ptah-operator.labels already writes on every
// object; a definition that set one of them would duplicate the key.
var releaseLabels = []string{
	"helm.sh/chart",
	"app.kubernetes.io/name",
	"app.kubernetes.io/instance",
	"app.kubernetes.io/version",
	"app.kubernetes.io/managed-by",
}

// bareScalar is what may be written as an unquoted YAML scalar: names,
// label keys and values, and the enum fields.
var bareScalar = regexp.MustCompile(`^[A-Za-z0-9][A-Za-z0-9._/-]*$`)

// sentinelShape is what every string sentinel looks like, so a value a
// template forgot to name among its parameters is refused here rather than
// shipped as text. An integer sentinel has no shape to scan for; the render
// test in this package catches one.
var sentinelShape = regexp.MustCompile(`__[A-Z][A-Z0-9_]*__`)

// emit writes t as a Helm template. It refuses a policy it cannot write
// faithfully rather than approximating one: a field this emitter does not
// know is a field the template would silently drop.
func emit(t template) (string, error) {
	if len(t.pairs) == 0 {
		return "", fmt.Errorf("%s: no policies", t.path)
	}
	e := &emitter{parameters: t.parameters}
	e.printf("{{- /*\nGenerated by hack/chartpolicies from %s.\nDo not edit: change the Go definition and run make chart-policies.\n*/ -}}\n", t.source)
	if t.condition != "" {
		e.printf("{{- if %s }}\n", t.condition)
	}
	for _, line := range t.preamble {
		e.printf("{{- %s -}}\n", line)
	}
	for index, pair := range t.pairs {
		if index > 0 {
			e.printf("---\n")
		}
		if err := e.policy(pair.policy); err != nil {
			return "", fmt.Errorf("%s: policy %d: %w", t.path, index, err)
		}
		e.printf("---\n")
		if err := e.binding(pair.binding); err != nil {
			return "", fmt.Errorf("%s: binding %d: %w", t.path, index, err)
		}
	}
	if t.condition != "" {
		e.printf("{{- end }}\n")
	}
	out := e.out.String()
	if leak := sentinelShape.FindString(out); leak != "" {
		return "", fmt.Errorf("%s: sentinel %s reached the template unsubstituted", t.path, leak)
	}
	return out, nil
}

type emitter struct {
	parameters []parameter
	out        strings.Builder
}

func (e *emitter) printf(format string, args ...any) {
	_, _ = fmt.Fprintf(&e.out, format, args...)
}

func (e *emitter) policy(p *admissionregistrationv1.ValidatingAdmissionPolicy) error {
	if p == nil {
		return errors.New("nil")
	}
	if err := e.head("ValidatingAdmissionPolicy", p.TypeMeta, p.ObjectMeta); err != nil {
		return err
	}
	spec := p.Spec
	switch {
	case spec.ParamKind != nil:
		return errors.New("paramKind is not supported")
	case len(spec.AuditAnnotations) != 0:
		return errors.New("auditAnnotations are not supported")
	case spec.FailurePolicy == nil:
		return errors.New("failurePolicy must be explicit")
	case spec.MatchConstraints == nil:
		return errors.New("matchConstraints must be set")
	case len(spec.Validations) == 0:
		return errors.New("no validations")
	}
	failurePolicy, err := e.scalar(string(*spec.FailurePolicy), bare)
	if err != nil {
		return fmt.Errorf("failurePolicy: %w", err)
	}
	e.printf("spec:\n")
	e.printf("  failurePolicy: %s\n", failurePolicy)
	e.printf("  matchConstraints:\n")
	if err := e.matchResources(spec.MatchConstraints, "    "); err != nil {
		return fmt.Errorf("matchConstraints: %w", err)
	}
	if len(spec.MatchConditions) != 0 {
		e.printf("  matchConditions:\n")
		for _, condition := range spec.MatchConditions {
			if err := e.namedExpression(condition.Name, condition.Expression); err != nil {
				return fmt.Errorf("matchCondition %q: %w", condition.Name, err)
			}
		}
	}
	if len(spec.Variables) != 0 {
		e.printf("  variables:\n")
		for _, variable := range spec.Variables {
			if err := e.namedExpression(variable.Name, variable.Expression); err != nil {
				return fmt.Errorf("variable %q: %w", variable.Name, err)
			}
		}
	}
	e.printf("  validations:\n")
	for index, validation := range spec.Validations {
		expression, err := e.scalar(validation.Expression, quoted)
		if err != nil {
			return fmt.Errorf("validation %d: %w", index, err)
		}
		e.printf("    - expression: %s\n", expression)
		if validation.Message != "" {
			message, err := e.scalar(validation.Message, quoted)
			if err != nil {
				return fmt.Errorf("validation %d message: %w", index, err)
			}
			e.printf("      message: %s\n", message)
		}
		if validation.MessageExpression != "" {
			message, err := e.scalar(validation.MessageExpression, quoted)
			if err != nil {
				return fmt.Errorf("validation %d messageExpression: %w", index, err)
			}
			e.printf("      messageExpression: %s\n", message)
		}
		if validation.Reason != nil {
			reason, err := e.scalar(string(*validation.Reason), bare)
			if err != nil {
				return fmt.Errorf("validation %d reason: %w", index, err)
			}
			e.printf("      reason: %s\n", reason)
		}
	}
	return nil
}

func (e *emitter) binding(b *admissionregistrationv1.ValidatingAdmissionPolicyBinding) error {
	if b == nil {
		return errors.New("nil")
	}
	if err := e.head("ValidatingAdmissionPolicyBinding", b.TypeMeta, b.ObjectMeta); err != nil {
		return err
	}
	spec := b.Spec
	switch {
	case spec.ParamRef != nil:
		return errors.New("paramRef is not supported")
	case spec.PolicyName == "":
		return errors.New("policyName must be set")
	case spec.MatchResources == nil:
		return errors.New("matchResources must be set")
	case len(spec.ValidationActions) == 0:
		return errors.New("no validationActions")
	}
	policyName, err := e.scalar(spec.PolicyName, bare)
	if err != nil {
		return fmt.Errorf("policyName: %w", err)
	}
	e.printf("spec:\n")
	e.printf("  policyName: %s\n", policyName)
	e.printf("  matchResources:\n")
	if err := e.matchResources(spec.MatchResources, "    "); err != nil {
		return fmt.Errorf("matchResources: %w", err)
	}
	actions := make([]string, len(spec.ValidationActions))
	for index, action := range spec.ValidationActions {
		if actions[index], err = e.scalar(string(action), bare); err != nil {
			return fmt.Errorf("validationActions: %w", err)
		}
	}
	e.printf("  validationActions: [%s]\n", strings.Join(actions, ", "))
	return nil
}

// head writes the apiVersion, kind and metadata of an object: its name, the
// release labels every chart object carries, and the labels the definition
// adds to them.
func (e *emitter) head(kind string, typeMeta metav1.TypeMeta, meta metav1.ObjectMeta) error {
	apiVersion := admissionregistrationv1.SchemeGroupVersion.String()
	if typeMeta.APIVersion != apiVersion || typeMeta.Kind != kind {
		return fmt.Errorf("typeMeta is %s %s, want %s %s", typeMeta.APIVersion, typeMeta.Kind, apiVersion, kind)
	}
	if meta.Name == "" {
		return errors.New("no name")
	}
	if meta.GenerateName != "" || meta.Namespace != "" || len(meta.Annotations) != 0 ||
		len(meta.OwnerReferences) != 0 || len(meta.Finalizers) != 0 {
		return errors.New("metadata carries more than a name and labels")
	}
	name, err := e.scalar(meta.Name, bare)
	if err != nil {
		return fmt.Errorf("name: %w", err)
	}
	e.printf("apiVersion: %s\nkind: %s\nmetadata:\n  name: %s\n", apiVersion, kind, name)
	e.printf("  labels:\n    {{- include \"ptah-operator.labels\" . | nindent 4 }}\n")
	keys := make([]string, 0, len(meta.Labels))
	for key := range meta.Labels {
		if slices.Contains(releaseLabels, key) {
			return fmt.Errorf("label %s is one ptah-operator.labels already writes", key)
		}
		keys = append(keys, key)
	}
	sort.Strings(keys)
	for _, key := range keys {
		if err := e.mapping("    ", key, meta.Labels[key]); err != nil {
			return fmt.Errorf("label %s: %w", key, err)
		}
	}
	return nil
}

func (e *emitter) matchResources(m *admissionregistrationv1.MatchResources, indent string) error {
	if len(m.ExcludeResourceRules) != 0 {
		return errors.New("excludeResourceRules are not supported")
	}
	if m.MatchPolicy != nil {
		policy, err := e.scalar(string(*m.MatchPolicy), bare)
		if err != nil {
			return fmt.Errorf("matchPolicy: %w", err)
		}
		e.printf("%smatchPolicy: %s\n", indent, policy)
	}
	if m.NamespaceSelector != nil {
		if err := e.selector("namespaceSelector", m.NamespaceSelector, indent); err != nil {
			return err
		}
	}
	if m.ObjectSelector != nil {
		if err := e.selector("objectSelector", m.ObjectSelector, indent); err != nil {
			return err
		}
	}
	if len(m.ResourceRules) == 0 {
		return nil
	}
	e.printf("%sresourceRules:\n", indent)
	for index, rule := range m.ResourceRules {
		if len(rule.ResourceNames) != 0 {
			return fmt.Errorf("rule %d: resourceNames are not supported", index)
		}
		if rule.Scope == nil {
			return fmt.Errorf("rule %d: scope must be explicit", index)
		}
		operations := make([]string, len(rule.Operations))
		for i, operation := range rule.Operations {
			operations[i] = string(operation)
		}
		for _, field := range []struct {
			name   string
			values []string
		}{
			{"apiGroups", rule.APIGroups},
			{"apiVersions", rule.APIVersions},
			{"operations", operations},
			{"resources", rule.Resources},
		} {
			list, err := e.list(field.values)
			if err != nil {
				return fmt.Errorf("rule %d %s: %w", index, field.name, err)
			}
			prefix := indent + "    "
			if field.name == "apiGroups" {
				prefix = indent + "  - "
			}
			e.printf("%s%s: %s\n", prefix, field.name, list)
		}
		scope, err := e.scalar(string(*rule.Scope), bare)
		if err != nil {
			return fmt.Errorf("rule %d scope: %w", index, err)
		}
		e.printf("%s    scope: %s\n", indent, scope)
	}
	return nil
}

func (e *emitter) selector(name string, selector *metav1.LabelSelector, indent string) error {
	if len(selector.MatchExpressions) != 0 {
		return fmt.Errorf("%s: matchExpressions are not supported", name)
	}
	if len(selector.MatchLabels) == 0 {
		e.printf("%s%s: {}\n", indent, name)
		return nil
	}
	e.printf("%s%s:\n%s  matchLabels:\n", indent, name, indent)
	keys := make([]string, 0, len(selector.MatchLabels))
	for key := range selector.MatchLabels {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	for _, key := range keys {
		if err := e.mapping(indent+"    ", key, selector.MatchLabels[key]); err != nil {
			return fmt.Errorf("%s %s: %w", name, key, err)
		}
	}
	return nil
}

// mapping writes one `key: value` line with both sides bare.
func (e *emitter) mapping(indent, key, value string) error {
	k, err := e.scalar(key, bare)
	if err != nil {
		return err
	}
	v, err := e.scalar(value, bare)
	if err != nil {
		return err
	}
	e.printf("%s%s: %s\n", indent, k, v)
	return nil
}

// namedExpression writes one `- name: / expression:` item of a
// matchConditions or variables list.
func (e *emitter) namedExpression(name, expression string) error {
	n, err := e.scalar(name, bare)
	if err != nil {
		return err
	}
	x, err := e.scalar(expression, quoted)
	if err != nil {
		return err
	}
	e.printf("    - name: %s\n      expression: %s\n", n, x)
	return nil
}

// list writes a flow sequence of literal strings. A parameter in a list is
// refused: no rule of these policies reads a release value.
func (e *emitter) list(values []string) (string, error) {
	items := make([]string, len(values))
	for index, value := range values {
		if _, args := e.substitute(value); len(args) != 0 {
			return "", fmt.Errorf("%q carries a parameter", value)
		}
		items[index] = strconv.Quote(value)
	}
	return "[" + strings.Join(items, ", ") + "]", nil
}

type scalarMode int

const (
	// bare writes the value as an unquoted YAML scalar: a name.
	bare scalarMode = iota
	// quoted writes the value as a double-quoted YAML scalar, through
	// Helm's quote where the template computes it: an expression or a
	// message.
	quoted
)

// scalar writes one string, as Helm text where it carries parameters and as
// a YAML literal where it does not.
func (e *emitter) scalar(value string, mode scalarMode) (string, error) {
	format, args := e.substitute(value)
	switch {
	case len(args) == 0:
		if mode == bare {
			if !bareScalar.MatchString(value) {
				return "", fmt.Errorf("%q cannot be written as a bare scalar", value)
			}
			return value, nil
		}
		return quoteLiteral(value)
	case format == "%s":
		if mode == bare {
			return "{{ " + args[0] + " }}", nil
		}
		return "{{ " + args[0] + " | quote }}", nil
	case format == `"%s"` && mode == quoted:
		// A Go-quoted parameter, as strconv.Quote wrote it: printf "%q" is
		// the same quoting in the template.
		return `{{ printf "%q" ` + argument(args[0]) + " | quote }}", nil
	}
	if strings.Contains(format, "`") {
		return "", fmt.Errorf("%q holds a backtick, which a template raw string cannot", value)
	}
	call := "printf `" + format + "`"
	for _, arg := range args {
		call += " " + argument(arg)
	}
	if mode == bare {
		return "{{ " + call + " }}", nil
	}
	return "{{ " + call + " | quote }}", nil
}

// substitute turns value into a printf format with %s where each parameter's
// sentinel stood, and the parameters' Helm expressions as the arguments in
// that order. Every other percent sign is escaped. A value with no parameter
// comes back with no arguments, and its format is not meant to be used.
func (e *emitter) substitute(value string) (string, []string) {
	var format strings.Builder
	var args []string
	rest := value
	for {
		index, found := -1, parameter{}
		for _, p := range e.parameters {
			i := strings.Index(rest, p.sentinel)
			if p.sentinel == "" || i < 0 {
				continue
			}
			if index < 0 || i < index || (i == index && len(p.sentinel) > len(found.sentinel)) {
				index, found = i, p
			}
		}
		if index < 0 {
			format.WriteString(strings.ReplaceAll(rest, "%", "%%"))
			return format.String(), args
		}
		format.WriteString(strings.ReplaceAll(rest[:index], "%", "%%"))
		format.WriteString("%s")
		args = append(args, found.helm)
		rest = rest[index+len(found.sentinel):]
	}
}

// argument parenthesizes a Helm call so it can be passed to printf.
func argument(helm string) string {
	if strings.ContainsAny(helm, " ") {
		return "(" + helm + ")"
	}
	return helm
}

// quoteLiteral writes a string the chart does not compute. A value that
// needs no escaping is a plain double-quoted scalar; one that does goes
// through Helm's quote from a raw string, which reads as the Go source does
// and renders the same %q form.
func quoteLiteral(value string) (string, error) {
	plain := `"` + value + `"`
	if strconv.Quote(value) == plain && !strings.Contains(value, "{{") && !strings.Contains(value, "}}") {
		return plain, nil
	}
	if strings.Contains(value, "`") {
		return "", fmt.Errorf("%q holds a backtick, which a template raw string cannot", value)
	}
	return "{{ `" + value + "` | quote }}", nil
}
